---
# handlers file for kafka
- name: restart kafka
  systemd:
    name: kafka
    state: restarted
    enabled: yes

- name: reload kafka
  systemd:
    name: kafka
    state: reloaded

- name: reload systemd
  systemd:
    daemon_reload: yes

