---
# defaults file for kafka
kafka_version: "3.4.0"  # Kafka version to install
scala_version: "2.13"    # Scala version for the Kafka build
kafka_download_url: "https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
broker_id: 1                 # Default broker ID
log_dirs: "/var/lib/kafka"    # Default log directory
kafka_host: "{{ inventory_hostname }}"  # Use the hostname as Kafka host
kafka_port: 9092              # Default Kafka port
zookeeper_connect: "localhost:2181"  # Default ZooKeeper address
